# Generated by Django 4.1 on 2022-09-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avgrating',
            unique_together={('tag', 'profile')},
        ),
    ]
