# Generated by Django 4.1 on 2022-09-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avgrating',
            name='id',
        ),
        migrations.AlterField(
            model_name='avgrating',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='avg_profile', serialize=False, to='accounts.profile'),
        ),
    ]
