# Generated by Django 4.1 on 2022-08-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ph_num',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
