# Generated by Django 4.1 on 2023-02-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_avgrating_avgassignmentsrating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='timingRating',
            new_name='timely_teacherRating',
        ),
    ]
