# Generated by Django 4.1 on 2023-02-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_timingrating_rate_timely_teacherrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='timely_teacherRating',
            new_name='timelyteacherRating',
        ),
    ]
