# Generated by Django 4.1 on 2023-02-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_assignmentsrating_rate_getreadytodoworkrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avgrating',
            name='avgActivitiesRating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='avgrating',
            name='avgControlRating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='avgrating',
            name='avgGraderRating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='avgrating',
            name='avgLectureRating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='avgrating',
            name='avgNotesRating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='avgrating',
            name='avgQuestioningRating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='BewareofquestioningRating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='ControlfreakRating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='ExtraactivitiesRating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='LectureheavyRating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='NotesprovidedRating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='ToughGraderRating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
