# Generated by Django 4.1 on 2023-02-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_avgrating_avgactivitiesrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_hint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
