# Generated by Django 4.1 on 2023-02-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tag_tag_hint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='clarityRating',
            new_name='ClarityRating',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='getreadytodoworkRating',
            new_name='GetreadytodoworkRating',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='skipclassyouwillnotpassRating',
            new_name='SkipclassyouwillnotpassRating',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='timelyteacherRating',
            new_name='TimelyteacherRating',
        ),
    ]
